config/routes.rb
Tinyblog::Engine.routes.draw do

  root :to => 'posts#index'

  get 'sitemap' => 'sitemap#index', :format => :xml, :as => :sitemap

  resources :posts, :only => [:index, :show]

  namespace :admin do 
    root :to => 'posts#index'
    resources :authors
    resources :posts, except: [:edit] do 
      member { put :restore }
      resource :status, only: [:update], controller: 'posts/status'
    end
    
    resource :editor, path: 'editor/:id',  only: [:edit, :update], controller: 'editor' 

    resource :editor, only: [:edit, :update], controller: 'posts/editor'
    resources :authors
    resources :pictures, :only => [:create]
  end
end

app/models/tinyblog/author.rb
module Tinyblog
  class Author < ActiveRecord::Base
    has_many :posts

    def fullname
      "#{first_name} #{last_name}"
    end

    def short_fullname 
      "#{first_name} #{last_name[0]}."
    end
  end
end

app/models/tinyblog/picture.rb
module Tinyblog
  class Picture < ActiveRecord::Base
     mount_uploader :data, TinyblogPictureUploader
     delegate :url, :to => :data
     
  end
end

app/models/tinyblog/post.rb
module Tinyblog
  class Post < ActiveRecord::Base
    acts_as_paranoid    
    include ::ActionView::Helpers::TextHelper

    belongs_to :author

    validates :published_at , presence: true
    validates :access_key , length: {is: 6}
    validates :title,   presence: true
    validates :body,    length: {minimum: 0, allow_nil: false}
    validates :author,  presence:  { message: 'must be present.'}

    scope :latest, -> { order('published_at DESC') }
    scope :active, -> { where(deleted_at: nil) }
    default_scope { active }

    after_initialize  :set_defaults
    before_validation :ensure_title_and_body


    extend FriendlyId
    friendly_id :title, use: [:history, :slugged, :finders]

    include Workflow
    workflow do
      state :drafting do
        event :publish, :transitions_to => :published
      end
      state :published do
        event :draft, :transitions_to => :drafting
      end
    end

    #
    # Short preview of post's body for use in the index.
    #
    def preview
      truncate(body, length: Tinyblog.post_preview_length, separator: "\n")
    end

    def view!
      self.increment!(:view_count)
    end

    def should_generate_new_friendly_id?
      title_changed?
    end

    private 
    #
    # Callback
    #
    def set_defaults
      return unless new_record?
      self.published_at ||= Time.now 
      self.access_key   ||= secure_key
    end

    def ensure_title_and_body
      self.title ||= "Untitled"
      self.body  ||= ""
    end

    def secure_key
      length = 6
      SecureRandom.hex(length/2)
    end

  end
end

app/controllers/tinyblog/admin/authors_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  module Admin
    class AuthorsController < BaseController
      
      respond_to :html
      
      def index
        @authors = Author.all
        respond_with @authors
      end

      def new
        @author = Author.new
      end

      def create
        @author = Author.new(author_params)
        if @author.save
          flash[:success] = t('tinyblog.authors.created')
        else
          flash[:warning] = t('tinyblog.authors.not_created')
        end

        respond_with @author, :location => admin_authors_path
      end

      def edit
        @author = Author.find(params[:id])
      end

      def update
        @author = Author.find(params[:id])
        if @author.update_attributes(author_params)
          flash[:notice] = t('tinyblog.authors.updated')
        else
          flash[:warning] = t('tinyblog.authors.not_updated')
        end

        respond_with @author, :location => admin_authors_path
      end

      def destroy
      end

      protected

        def author_params
          params.require(:author).permit(:first_name, :last_name, :bio, :twitter, :facebook, :gplus)
        end
    end
  end
end

app/controllers/tinyblog/admin/base_controller.rb
module Tinyblog
  module Admin

    class BaseController < ApplicationController
      before_filter :authorize_tinyblog_admin!

      layout Tinyblog.admin_layout

      private

        def authorize_tinyblog_admin!
          if !tinyblog_admin_logged_in?
            flash[:warning] = t('tinyblog.errors.access_denied')
            redirect_to root_path 
          end
        end
    end
    
  end
end

app/controllers/tinyblog/admin/editor_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  module Admin
  
    class EditorController < BaseController

      respond_to :html

      layout 'tinyblog/editor'

      def edit
        @post = Post.find(params[:id])
      end


      def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
          flash[:notice] = t('tinyblog.posts.updated')
        else
          flash[:warning] = t('tinyblog.posts.not_updated')
        end
        respond_with @post, :location => edit_admin_editor_path(@post)
      end

      private

      def post_params
        params.require(:post).permit(:title, :body)
      end

    end
  end
end

app/controllers/tinyblog/admin/pictures_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  module Admin
    class PicturesController < BaseController

      def create
        @picture = Picture.new(:data => params[:file])

        if @picture.save
          render :json => { :filename => @picture.url }
        else
          render :nothing => true
        end
      end
    end
  end
end

app/controllers/tinyblog/admin/posts/editor_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  module Admin
    module Posts
      class EditorController < BaseController

        def edit
          @post = Post.find(params[:id])
        end


        def update
          @post = Post.find(params[:id])
          if @post.update_attributes(post_params)
            flash[:notice] = t('tinyblog.posts.updated')
          else
            flash[:warning] = t('tinyblog.posts.not_updated')
          end

          respond_with @post, :location => edit_admin_post_editor_path(@post)
        end

      end
    end
  end
end

app/controllers/tinyblog/admin/posts/status_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  module Admin
    module Posts
      class StatusController < BaseController

        def update
          @post = Post.find(params[:post_id])
          case params[:status]
          when 'drafting' then @post.draft!
          when 'published' then @post.publish!
          end

          redirect_to admin_post_path(@post)
        end

        


        
      end
    end
  end
end

app/controllers/tinyblog/admin/posts_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  module Admin
    class PostsController < BaseController
      
      respond_to :html

      def index
        params[:tab] ||= 'All'
        @posts = case params[:tab]
        when 'All'    then Post.all
        when 'Draft' then Post.with_drafting_state
        when 'Published' then Post.with_published_state
        when 'Trash' then Post.only_deleted
        end
      end

      def show
        @post = Post.find(params[:id])
      end

      def new
        @post = Post.new
      end

      def create
        @post = Post.create(author: Author.first)
        if @post.valid?
          redirect_to edit_admin_editor_path(@post)
        else
          flash[:warning] = t('tinyblog.posts.not_created')
          redirect_to admin_posts_path
        end
      end

      def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
          flash[:notice] = t('tinyblog.posts.updated')
        else
          flash[:warning] = t('tinyblog.posts.not_updated')
        end

        respond_with @post, :location => admin_post_path(@post)
      end

      def destroy
        @post = Post.find(params[:id])
        @post.destroy
        
        flash[:notice] = t('tinyblog.posts.deleted')
        redirect_to admin_posts_path
      end

      def restore
        @post = Post.only_deleted.find(params[:id])
        Post.restore(@post.id)
        flash[:notice] = t('tinyblog.posts.restored')
        redirect_to admin_posts_path
      end

      protected

        def post_params
          params.require(:post).permit(:author_id, :meta_description, :"published_at(1i)", :"published_at(2i)", :"published_at(3i)")
        end
    end
  end
end

app/controllers/tinyblog/application_controller.rb
module Tinyblog
  class ApplicationController < ::ApplicationController

    rescue_from ActiveRecord::RecordNotFound, with: :redirect_not_found
    
    layout Tinyblog.layout

    private

    def tinyblog_admin_logged_in?
      tinyblog_user and tinyblog_user.tinyblog_admin?
    end
    helper_method :tinyblog_admin_logged_in?

    def redirect_not_found
      redirect_to posts_path
    end
    
  end
end

app/controllers/tinyblog/posts_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  class PostsController < ApplicationController
    
    before_action :load_post, only: :show
    before_action :authorize_post, only: :show
    before_action :redirect_old_slugs, only: :show

    respond_to :html, :rss

    def index
      @posts = Post.with_published_state.latest.includes(:author).all
      @latest_posts = Post.with_published_state.latest.limit(Tinyblog.max_latest_posts).all if Tinyblog.latest_posts_on
      respond_with @posts
    end

    def show
      @post.view! unless tinyblog_admin_logged_in?

      @author = @post.author
      @latest_posts = Post.with_published_state.latest.limit(Tinyblog.max_latest_posts).all if Tinyblog.latest_posts_on

      respond_with @post
    end

    private

    def load_post
      @post = Post.find(params[:id])
    end

    def authorize_post
      if tinyblog_admin_logged_in? or
        @post.published? or
        @post.access_key == params[:access_key]
        return true
      else
        raise ActiveRecord::RecordNotFound
      end
    end

    # If post slug has chnaged due to title change then 
    # need to redirect any requests to the old slug names
    # to the current one.
    def redirect_old_slugs
      if request.path != post_path(@post)
        redirect_to(post_path(@post), :status => :moved_permanently) and return
      end
    end
  end
end

app/controllers/tinyblog/sitemap_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  class SitemapController < ApplicationController
  
    def index
      @static_pages = [root_url]
      # Display all the posts in reverse chronological order
      @posts = Post.all.sort.reverse
      respond_to do |format|
        format.xml
      end
    end
    
  end
end

app/helpers/tinyblog/admin/authors_helper.rb
module Tinyblog
  module Admin::AuthorsHelper
  end
end

app/helpers/tinyblog/admin/pictures_helper.rb
module Tinyblog
  module Admin::PicturesHelper
  end
end

app/helpers/tinyblog/admin/posts/status_helper.rb
module Tinyblog
  module Admin::Posts::StatusHelper
  end
end

app/helpers/tinyblog/application_helper.rb
module Tinyblog
  module ApplicationHelper
  end
end

app/helpers/tinyblog/posts_helper.rb
module Tinyblog
  module PostsHelper
    def render_content(content)
      renderer = Redcarpet::Render::HTML.new(hard_wrap: true)
      markdown = Redcarpet::Markdown.new(renderer, extensions = {})
      markdown.render(content).html_safe
    end

    def cache_key_for_posts
      count          = Post.count
      max_updated_at = Post.maximum(:updated_at).try(:utc).try(:to_s, :number)
      "posts/all-#{count}-#{max_updated_at}"
    end
  end
end

app/helpers/tinyblog/sitemap_helper.rb
module Tinyblog
  module SitemapHelper
  end
end

app/views/layouts/tinyblog/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinyblog</title>
    <%= stylesheet_link_tag    "tinyblog/tinyblog", media: "all" %>
    <%= javascript_include_tag "tinyblog/tinyblog" %>
    <%= yield :head if content_for? :head %>
    <%= csrf_meta_tags %>
  </head>
  <body class="admin <%= controller_name %> <%= action_name %>">

    <% unless controller_name == 'editor' %>
      <nav class="navbar navbar-tinyblog" role="navigation">
         <div class="container">
           
           <div class="navbar-header">
             <button type="button" class="navbar-toggle" data-toggle="collapse">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
             </button>
             <%= link_to "Site", Tinyblog.blog_name_links_to, :class => "navbar-brand" %>
           </div>


           <div class="collapse navbar-collapse">
             <div class="nav-bar">
               <ul class="nav navbar-nav navbar-right">
                 <li><%= link_to t('tinyblog.nav.admin.view_blog'), posts_path %></li>
                 <li><%= link_to t('tinyblog.nav.admin.posts'), admin_posts_path %></li>
                 <li><%= link_to t('tinyblog.nav.admin.authors'), admin_authors_path %></li>
               </ul>
             </div>
           </div>  
         </div>
       </nav>
     <% end %>

    <%= render 'tinyblog/shared/messages' %>
    <%= yield %>

  </body>
</html>

app/views/layouts/tinyblog/default.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= content_for?(:title) ? yield(:title) : Tinyblog.blog_name  %></title>

    <% if content_for? :meta_description %>
      <meta name="Description" content="<%= yield :meta_description %>"></meta>
    <% end %>

    <%= stylesheet_link_tag    "tinyblog/tinyblog", media: "all" %>
    <%= javascript_include_tag "tinyblog/tinyblog" %>
    <%= yield :head if content_for? :head %>
    <%= csrf_meta_tags %>

  </head>

  <body>

    <nav class="navbar navbar-default" role="navigation">
       <div class="container">
         
         <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <%= link_to Tinyblog.blog_name, Tinyblog.blog_name_links_to || root_path, :class => 'navbar-brand' %>
         </div>


         <div class="collapse navbar-collapse">
           <div class="nav-bar">
             <ul class="nav navbar-nav navbar-right">
               <% if tinyblog_admin_logged_in? %>
                 <li><%= link_to t('tinyblog.nav.frontend.to_admin'), admin_root_path %></li>
               <% end %>
             </ul>
           </div>
         </div>  
       </div>
     </nav>

     <%= render 'tinyblog/shared/messages' %>

    <%= yield %>

  </body>
</html>

app/views/layouts/tinyblog/editor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinyblog</title>
    <%= stylesheet_link_tag    "tinyblog/tinyblog", media: "all" %>
    <%= javascript_include_tag "tinyblog/tinyblog" %>
    <%= yield :head if content_for? :head %>
    <%= csrf_meta_tags %>
  </head>
  <body class="admin <%= controller_name %> <%= action_name %>">
    
    <%= yield %>

  </body>
</html>