config/routes.rb
Tinyblog::Engine.routes.draw do

  root :to => 'posts#index'

  get 'sitemap' => 'sitemap#index', :format => :xml, :as => :sitemap

  resources :posts, :only => [:index, :show]

  namespace :admin do 
    root :to => 'posts#index'
    resources :authors
    resources :posts, except: [:edit] do 
      member { put :restore }
      resource :status, only: [:update], controller: 'posts/status'
    end
    
    resource :editor, path: 'editor/:id',  only: [:edit, :update], controller: 'editor' 

    resource :editor, only: [:edit, :update], controller: 'posts/editor'
    resources :authors
    resources :pictures, :only => [:create]
  end
end

app/models/tinyblog/author.rb
module Tinyblog
  class Author < ActiveRecord::Base
    has_many :posts

    def fullname
      "#{first_name} #{last_name}"
    end

    def short_fullname 
      "#{first_name} #{last_name[0]}."
    end
  end
end

app/controllers/tinyblog/admin/authors_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  module Admin
    class AuthorsController < BaseController
      
      respond_to :html
      
      def index
        @authors = Author.all
        respond_with @authors
      end

      def new
        @author = Author.new
      end

      def create
        @author = Author.new(author_params)
        if @author.save
          flash[:success] = t('tinyblog.authors.created')
        else
          flash[:warning] = t('tinyblog.authors.not_created')
        end

        respond_with @author, :location => admin_authors_path
      end

      def edit
        @author = Author.find(params[:id])
      end

      def update
        @author = Author.find(params[:id])
        if @author.update_attributes(author_params)
          flash[:notice] = t('tinyblog.authors.updated')
        else
          flash[:warning] = t('tinyblog.authors.not_updated')
        end

        respond_with @author, :location => admin_authors_path
      end

      def destroy
      end

      protected

        def author_params
          params.require(:author).permit(:first_name, :last_name, :bio, :twitter, :facebook, :gplus)
        end
    end
  end
end

app/helpers/tinyblog/admin/authors_helper.rb
module Tinyblog
  module Admin::AuthorsHelper
  end
end

app/views/tinyblog/admin/authors/_form.html.erb
<%= simple_form_for [tinyblog, :admin, @author] do |f| %>
  <div class="panel-body">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :bio %>
    <%= f.input :twitter %>
    <%= f.input :facebook %>
    <%= f.input :gplus %>
  </div>
  <div class="panel-footer">
    <%= f.button :submit, @author.new_record? ? 'Save' : 'Update', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/tinyblog/admin/authors/edit.html.erb
<div class="container">

  <div class="row">

    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h1 class="panel-title">Edit Author</h1>
        </div>

        
        <%= render 'form' %>
        
      </div>
    </div>

  </div>
  
</div>

app/views/tinyblog/admin/authors/index.html.erb
<div class="container">
  
  <div class="panel-header">
    <h1>Authors</h1>
  </div>

  <table class="table authors">
    <tbody>
      <% @authors.each do |author| %>    
        <tr>
          <td>
            <%= author.fullname %>
          </td>
          <td>
            <%= link_to t('tinyblog.ui.edit'), edit_admin_author_path(author), :class => "btn btn-default btn-sm" %>
          </td>
          <td>
            <%= button_to t('tinyblog.ui.delete'), admin_author_path(author), :method => :delete, :class => 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>




  <%= button_to t('tinyblog.authors.new'), new_admin_author_path, :method => :get, :class => 'btn btn-primary' %>

</div>

app/views/tinyblog/admin/authors/new.html.erb
<div class="container">

  <div class="row">

    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h1 class="panel-title">Create Author</h1>
        </div>

        
        <%= render 'form' %>
        
      </div>
    </div>

  </div>
  
</div>