config/routes.rb
Tinyblog::Engine.routes.draw do

  root :to => 'posts#index'

  get 'sitemap' => 'sitemap#index', :format => :xml, :as => :sitemap

  resources :posts, :only => [:index, :show]

  namespace :admin do 
    root :to => 'posts#index'
    resources :authors
    resources :posts, except: [:edit] do 
      member { put :restore }
      resource :status, only: [:update], controller: 'posts/status'
    end
    
    resource :editor, path: 'editor/:id',  only: [:edit, :update], controller: 'editor' 

    resource :editor, only: [:edit, :update], controller: 'posts/editor'
    resources :authors
    resources :pictures, :only => [:create]
  end
end

app/controllers/tinyblog/admin/editor_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  module Admin
  
    class EditorController < BaseController

      respond_to :html

      layout 'tinyblog/editor'

      def edit
        @post = Post.find(params[:id])
      end


      def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
          flash[:notice] = t('tinyblog.posts.updated')
        else
          flash[:warning] = t('tinyblog.posts.not_updated')
        end
        respond_with @post, :location => edit_admin_editor_path(@post)
      end

      private

      def post_params
        params.require(:post).permit(:title, :body)
      end

    end
  end
end

app/controllers/tinyblog/admin/posts/editor_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  module Admin
    module Posts
      class EditorController < BaseController

        def edit
          @post = Post.find(params[:id])
        end


        def update
          @post = Post.find(params[:id])
          if @post.update_attributes(post_params)
            flash[:notice] = t('tinyblog.posts.updated')
          else
            flash[:warning] = t('tinyblog.posts.not_updated')
          end

          respond_with @post, :location => edit_admin_post_editor_path(@post)
        end

      end
    end
  end
end

app/views/tinyblog/admin/editor/edit.html.erb
<div class="flash-container">
  <%= render 'tinyblog/shared/messages' %>
</div>

<div class="container">
  <div class="row">

    <%= form_for @post, url: admin_editor_url, html: {class: 'editor' } do |f| %>
      <div class="main">
        <div class="post-container">
          <div class="post-header">
            <%= f.text_field :title %>
          </div>
          <div class="post-body">
            <%= f.text_area :body, data: {'image-upload-url' => admin_pictures_url()} %>
          </div>
        </div>
      </div>
    
      <div class="side">
        <div class="actions">
            <%= f.button t('tinyblog.ui.save'), :class => 'btn btn-block btn-primary' , data: {behaviour: 'save_post' } %>
  
            <%= link_to t('tinyblog.ui.cancel'), admin_post_path(@post), class: 'btn btn-block btn-default' %> 
          </fieldset>
      </div>
  
    <% end %>

  </div>
  
</div>


<script type="text/javascript">
  codemirror = CodeMirror.fromTextArea(document.getElementById('post_body'), {
          mode:           'gfm',
          tabMode:        'indent',
          tabindex:       '2',
          theme: 'tinyblog',
          cursorScrollMargin: 10,
          lineWrapping:   true,
          extraKeys: {
              Home:   'goLineLeft',
              End:    'goLineRight',
              Enter:  'newlineAndIndentContinueMarkdownList'
          }
   })

  codemirror.on('change', function(){
    window.setDirty(true);
  });

  $('button[data-behaviour="save_post"]').on('click', function(){
    window.setDirty(false);
  })

  options = {
    uploadUrl: $("textarea#post_body").data('image-upload-url'),
    allowedTypes: ["image/jpeg", "image/png", "image/jpg", "image/gif"],
    extraParams: { 
      authenticity_token: $('input[name="authenticity_token"]').attr('value') 
    },
    progressText: "![Uploading file...]()",
    urlText: "![a picture]({filename})",
    errorText: "Error uploading file"
  }

  inlineAttach.attachToCodeMirror(codemirror, options);   
</script>