config/routes.rb
Tinyblog::Engine.routes.draw do

  root :to => 'posts#index'

  get 'sitemap' => 'sitemap#index', :format => :xml, :as => :sitemap

  resources :posts, :only => [:index, :show]

  namespace :admin do 
    root :to => 'posts#index'
    resources :authors
    resources :posts, except: [:edit] do 
      member { put :restore }
      resource :status, only: [:update], controller: 'posts/status'
    end
    
    resource :editor, path: 'editor/:id',  only: [:edit, :update], controller: 'editor' 

    resource :editor, only: [:edit, :update], controller: 'posts/editor'
    resources :authors
    resources :pictures, :only => [:create]
  end
end

app/models/tinyblog/post.rb
module Tinyblog
  class Post < ActiveRecord::Base
    acts_as_paranoid    
    include ::ActionView::Helpers::TextHelper

    belongs_to :author

    validates :published_at , presence: true
    validates :access_key , length: {is: 6}
    validates :title,   presence: true
    validates :body,    length: {minimum: 0, allow_nil: false}
    validates :author,  presence:  { message: 'must be present.'}

    scope :latest, -> { order('published_at DESC') }
    scope :active, -> { where(deleted_at: nil) }
    default_scope { active }

    after_initialize  :set_defaults
    before_validation :ensure_title_and_body


    extend FriendlyId
    friendly_id :title, use: [:history, :slugged, :finders]

    include Workflow
    workflow do
      state :drafting do
        event :publish, :transitions_to => :published
      end
      state :published do
        event :draft, :transitions_to => :drafting
      end
    end

    #
    # Short preview of post's body for use in the index.
    #
    def preview
      truncate(body, length: Tinyblog.post_preview_length, separator: "\n")
    end

    def view!
      self.increment!(:view_count)
    end

    def should_generate_new_friendly_id?
      title_changed?
    end

    private 
    #
    # Callback
    #
    def set_defaults
      return unless new_record?
      self.published_at ||= Time.now 
      self.access_key   ||= secure_key
    end

    def ensure_title_and_body
      self.title ||= "Untitled"
      self.body  ||= ""
    end

    def secure_key
      length = 6
      SecureRandom.hex(length/2)
    end

  end
end

app/controllers/tinyblog/admin/posts/editor_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  module Admin
    module Posts
      class EditorController < BaseController

        def edit
          @post = Post.find(params[:id])
        end


        def update
          @post = Post.find(params[:id])
          if @post.update_attributes(post_params)
            flash[:notice] = t('tinyblog.posts.updated')
          else
            flash[:warning] = t('tinyblog.posts.not_updated')
          end

          respond_with @post, :location => edit_admin_post_editor_path(@post)
        end

      end
    end
  end
end

app/controllers/tinyblog/admin/posts/status_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  module Admin
    module Posts
      class StatusController < BaseController

        def update
          @post = Post.find(params[:post_id])
          case params[:status]
          when 'drafting' then @post.draft!
          when 'published' then @post.publish!
          end

          redirect_to admin_post_path(@post)
        end

        


        
      end
    end
  end
end

app/controllers/tinyblog/admin/posts_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  module Admin
    class PostsController < BaseController
      
      respond_to :html

      def index
        params[:tab] ||= 'All'
        @posts = case params[:tab]
        when 'All'    then Post.all
        when 'Draft' then Post.with_drafting_state
        when 'Published' then Post.with_published_state
        when 'Trash' then Post.only_deleted
        end
      end

      def show
        @post = Post.find(params[:id])
      end

      def new
        @post = Post.new
      end

      def create
        @post = Post.create(author: Author.first)
        if @post.valid?
          redirect_to edit_admin_editor_path(@post)
        else
          flash[:warning] = t('tinyblog.posts.not_created')
          redirect_to admin_posts_path
        end
      end

      def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
          flash[:notice] = t('tinyblog.posts.updated')
        else
          flash[:warning] = t('tinyblog.posts.not_updated')
        end

        respond_with @post, :location => admin_post_path(@post)
      end

      def destroy
        @post = Post.find(params[:id])
        @post.destroy
        
        flash[:notice] = t('tinyblog.posts.deleted')
        redirect_to admin_posts_path
      end

      def restore
        @post = Post.only_deleted.find(params[:id])
        Post.restore(@post.id)
        flash[:notice] = t('tinyblog.posts.restored')
        redirect_to admin_posts_path
      end

      protected

        def post_params
          params.require(:post).permit(:author_id, :meta_description, :"published_at(1i)", :"published_at(2i)", :"published_at(3i)")
        end
    end
  end
end

app/controllers/tinyblog/posts_controller.rb
require_dependency "tinyblog/application_controller"

module Tinyblog
  class PostsController < ApplicationController
    
    before_action :load_post, only: :show
    before_action :authorize_post, only: :show
    before_action :redirect_old_slugs, only: :show

    respond_to :html, :rss

    def index
      @posts = Post.with_published_state.latest.includes(:author).all
      @latest_posts = Post.with_published_state.latest.limit(Tinyblog.max_latest_posts).all if Tinyblog.latest_posts_on
      respond_with @posts
    end

    def show
      @post.view! unless tinyblog_admin_logged_in?

      @author = @post.author
      @latest_posts = Post.with_published_state.latest.limit(Tinyblog.max_latest_posts).all if Tinyblog.latest_posts_on

      respond_with @post
    end

    private

    def load_post
      @post = Post.find(params[:id])
    end

    def authorize_post
      if tinyblog_admin_logged_in? or
        @post.published? or
        @post.access_key == params[:access_key]
        return true
      else
        raise ActiveRecord::RecordNotFound
      end
    end

    # If post slug has chnaged due to title change then 
    # need to redirect any requests to the old slug names
    # to the current one.
    def redirect_old_slugs
      if request.path != post_path(@post)
        redirect_to(post_path(@post), :status => :moved_permanently) and return
      end
    end
  end
end

app/helpers/tinyblog/admin/posts/status_helper.rb
module Tinyblog
  module Admin::Posts::StatusHelper
  end
end

app/helpers/tinyblog/posts_helper.rb
module Tinyblog
  module PostsHelper
    def render_content(content)
      renderer = Redcarpet::Render::HTML.new(hard_wrap: true)
      markdown = Redcarpet::Markdown.new(renderer, extensions = {})
      markdown.render(content).html_safe
    end

    def cache_key_for_posts
      count          = Post.count
      max_updated_at = Post.maximum(:updated_at).try(:utc).try(:to_s, :number)
      "posts/all-#{count}-#{max_updated_at}"
    end
  end
end

app/views/tinyblog/admin/posts/edit.html.erb
<div class="container">
  <div class="row">

    <%= form_for [tinyblog, :admin, @post], html: {class: 'editor' } do |f| %>
      <div class="main">
        <div class="post-container">
          <div class="post-header">
            <%= f.text_field :title %>
          </div>
          <div class="post-body">
            <%= f.text_area :body, data: {'image-upload-url' => admin_pictures_url()} %>
          </div>
        </div>
      </div>
    
      <div class="side">
        <div class="actions">
            <%= f.button t('tinyblog.ui.save'), :class => 'btn btn-block btn-primary' , data: {behaviour: 'save_post' } %>
  
            <%= link_to t('tinyblog.ui.cancel'), admin_post_path(@post), class: 'btn btn-block btn-default' %> 
          </fieldset>
      </div>
  
    <% end %>

  </div>
  
</div>


<script type="text/javascript">
  codemirror = CodeMirror.fromTextArea(document.getElementById('post_body'), {
          mode:           'gfm',
          tabMode:        'indent',
          tabindex:       '2',
          theme: 'tinyblog',
          cursorScrollMargin: 10,
          lineWrapping:   true,
          extraKeys: {
              Home:   'goLineLeft',
              End:    'goLineRight',
              Enter:  'newlineAndIndentContinueMarkdownList'
          }
   })

  codemirror.on('change', function(){
    window.setDirty(true);
  });

  $('button[data-behaviour="save_post"]').on('click', function(){
    window.setDirty(false);
  })

  options = {
    uploadUrl: $("textarea#post_body").data('image-upload-url'),
    allowedTypes: ["image/jpeg", "image/png", "image/jpg", "image/gif"],
    extraParams: { 
      authenticity_token: $('input[name="authenticity_token"]').attr('value') 
    },
    progressText: "![Uploading file...]()",
    urlText: "![a picture]({filename})",
    errorText: "Error uploading file"
  }

  inlineAttach.attachToCodeMirror(codemirror, options);   
</script>

app/views/tinyblog/admin/posts/index.html.erb
<div class="container">
  <div class="col-sm-2 col-sm-offset-1">
    <div class="side">
      <div class="actions">
        <%= link_to t('tinyblog.posts.new'), admin_posts_path, :method => :post, :class => 'btn btn-primary' %>

        <ul>
          <%= content_tag :li, class: ('active' if params[:tab] == 'All' ) do %>
            <%= link_to 'All', admin_posts_path(tab: 'All') %>
          <% end %>

          <%= content_tag :li, class: ('active' if params[:tab] == 'Draft' ) do %>
            <%= link_to 'Drafts', admin_posts_path(tab: 'Draft') %>
          <% end %>

          <%= content_tag :li, class: ('active' if params[:tab] == 'Published' ) do %>
            <%= link_to 'Published', admin_posts_path(tab: 'Published') %>
          <% end %>

          <%= content_tag :li, class: ('active' if params[:tab] == 'Trash' ) do %>
            <%= link_to 'Trash', admin_posts_path(tab: 'Trash') %>
          <% end %>
        </div>
      </ul>
    </div>
  </div>

  <div class="col-sm-8">
    <div class="main">
      <div class="posts-container">
        <h1><%= params[:tab].capitalize %> Posts</h1>
        <table class="posts">
          <tbody>
            <% @posts.each do |post| %>
              <%= content_tag_for :tr, post, data: {behaviour: 'has_hover_content'} do %>
                
                <td class="post-author">
                  <%= post.author.short_fullname %>
                </td>   

                <td class="post-title">
                  <%= link_to_unless post.destroyed?, post.title, admin_post_path(post) %>
                </td>

                <td class="post-actions">
                  <% if post.destroyed? %>

                    <%= link_to t('tinyblog.ui.restore'), restore_admin_post_path(post), :method => :put%>              

                  <% else %>

                    <%= link_to t('tinyblog.ui.delete'), admin_post_path(post), :method => :delete  %>

                  <% end %>
                </td>
              <% end %>
            <% end %>
          </tbody>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/tinyblog/admin/posts/show.html.erb
<div class="container-fixed">
  <div class="row">
    <div class="breadcrumbs">
      <%= link_to 'Back to posts', admin_posts_path %>
    </div>
  </div>
  <div class="row">

    <div class="main">  
      <div class="paper">
          <div class="paper-header">
            <h1 class="title">
              <%= @post.title %>
            </h1>

          </div>
          <div class="paper-toolbar">
            <%= simple_form_for [tinyblog, :admin, @post], defaults: {required: false}, html: {class: 'form-inline'} do |f| %>
              <%= f.association :author, 
                                :collection => Tinyblog::Author.all, 
                                label: 'By:', 
                                :label_method => :short_fullname, 
                                :value_method => :id, 
                                :include_blank => false, 
                                input_html: {class: 'input-xs'} %>

              <%= f.input :published_at, 
                          as: :date,
                          label: 'On:',
                          input_html: {
                            class: 'input-xs'
                          } %>     

              <%= f.button :submit, t('tinyblog.ui.update'), class: 'btn btn-xs btn-default'  %>
            <% end %>
          </div>
          <div class="paper-body">
            <%= simple_format(@post.body) %>
          </div>

          <div class="paper-footer">
            <%= simple_form_for [tinyblog, :admin, @post], defaults: {required: false} do |f| %>
              <div class="row">
                <%= f.input :meta_description, wrapper_html: {class: 'col-sm-6'}, input_html: {class: 'input-xs'} %>
              </div>
              <%= f.button :submit, 'Update meta', class: 'btn btn-xs btn-default' %>
            <% end %>
            <div class="share-url">
              Share URL: <%= post_url(@post, access_key: @post.access_key) %>
            </div>  
          </div>
      </div>
    </div>

    
    <div class="side">
      <div class="actions">
          <%= link_to t('tinyblog.posts.edit'), edit_admin_editor_path(@post), :class => 'btn btn-block btn-default btn-lg' %>
          <ul class="actions-secondary">
            <li><%= link_to t('tinyblog.posts.view') + '...', post_path(@post, preview: true) %></li>
            <li><%= link_to t('tinyblog.posts.delete') + '...', admin_post_path(@post), method: :delete %></li>
            <% if @post.drafting? %>
            <li><%= link_to t('tinyblog.posts.publish') + '...', admin_post_status_path(@post, status: 'published'), method: :patch %> </li>
            <% else %>
              <li><%= link_to t('tinyblog.posts.draft') + '...', admin_post_status_path(@post, status: 'drafting'), method: :patch %> </li>
            <% end %>
          </ul>
      </div>
    </div>

  </div>
</div>